Update rename controler and index and add show controller and route
WildCodeSchool/Rogue-One_Symfony pull request #25
Opened 2024-02-21 20:39 UTC by chouaibj

2024-02-21 22:59 UTC, joelmayemba approved these changes

2024-02-22 08:59 UTC, Benja-san requested changes

2024-02-22 08:59 UTC, Benja-san commented on src/Controller/ProductController.php
> +    public function show(int $id, ProductRepository $productRepository): Response
Use param converter, Product $product instead of ProductRepository then you won't even have to fetch it. Symfony will make it for you

2024-02-22 13:25 UTC, Benja-san approved these changes

2024-02-22 13:34 UTC, merged