Add FAQ to the footer
WildCodeSchool/Rogue-One_Symfony pull request #26
Opened 2024-02-22 10:31 UTC by joelmayemba

2024-02-22 13:47 UTC, Benja-san requested changes

2024-02-22 13:47 UTC, Benja-san commented on templates/faq/index.html.twig
> +	<div class="single-mocktail section">
no h1 in this page. + use html semantic for better referencing like section / ul & li etc...

2024-02-23 08:05 UTC, chouaibj approved these changes

2024-02-23 09:17 UTC, Benja-san approved these changes

2024-02-23 09:33 UTC, merged