Update fix
WildCodeSchool/Rogue-One_Symfony pull request #29
Opened 2024-02-22 16:25 UTC by chouaibj

2024-02-22 17:10 UTC, joelmayemba approved these changes

2024-02-23 09:11 UTC, Benja-san requested changes

2024-02-23 09:11 UTC, Benja-san commented on assets/app.js
mocktail / about / contact and admin won't be on every pages. 
Create a corresponding js file, and map it like you did for app.js for each ressource.
e.G. : mocktail.js, will host imports for mocktail detail page, and will be added as an entry to the webpack file (restart yarn after configuring it)

2024-02-23 09:11 UTC, Benja-san commented on webpack.config.js
refactror your entries if you want to use tdstyleentry : https://symfonycasts.com/screencast/webpack-encore/add-style-entry

2024-02-23 10:43 UTC, Benja-san approved these changes

2024-02-23 10:44 UTC, merged