Migration page about us
WildCodeSchool/Rogue-One_Symfony pull request #3
Opened 2024-02-19 15:21 UTC by chouaibj

2024-02-19 16:04 UTC, joelmayemba approved these changes

2024-02-19 16:19 UTC, Benja-san requested changes

2024-02-19 16:19 UTC, Benja-san commented on src/Controller/AboutUsController.php
> +            'pageName' => 'AboutUs',
camel case for page name ? Is your website in English ?

2024-02-19 16:19 UTC, Benja-san commented on templates/about_us/index.html.twig
> +<div class="apropos-page section">
if no main tag in base.html.twig put it here

2024-02-20 09:45 UTC, Benja-san requested changes

2024-02-20 09:45 UTC, Benja-san commented on templates/about_us/index.html.twig
> +{% endblock %} {% block main %}
there is no block main in your base.html.twig

2024-02-20 09:45 UTC, Benja-san commented on templates/about_us/index.html.twig
> +<div class="apropos-page section">
sorry for the misscomprehension, rename this div into main, since you don't have a main tag wrapping your body block in your base.html.twig

2024-02-20 10:16 UTC, Benja-san approved these changes

2024-02-20 10:20 UTC, merged