Add data fixtures
WildCodeSchool/Rogue-One_Symfony pull request #39
Opened 2024-02-26 06:59 UTC by joelmayemba

2024-02-26 08:14 UTC, chouaibj approved these changes

2024-02-26 11:11 UTC, Benja-san requested changes
please rename your "pageName" variable in each controller to correspond with the page rendering

2024-02-26 14:57 UTC, Benja-san requested changes

2024-02-26 14:57 UTC, Benja-san commented on templates/faq/index.html.twig
think about title block, and add ul li for faq content loop

2024-02-27 08:24 UTC, Benja-san approved these changes

2024-02-27 08:26 UTC, merged