Migration page index of Mocktail, set css and js
WildCodeSchool/Rogue-One_Symfony pull request #4
Opened 2024-02-19 15:41 UTC by chouaibj

2024-02-19 16:04 UTC, joelmayemba approved these changes

2024-02-20 09:40 UTC, Benja-san requested changes

2024-02-20 09:40 UTC, Benja-san commented on assets/js/filters.js
rename this file mocktailsFilter for better understanding of the file

2024-02-20 09:40 UTC, Benja-san commented on assets/styles/pages/mocktails.css
> +    .contact-page #contact-form {
contact page styling has nothing to do in your mocktail css file

2024-02-20 09:40 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +            <div class="row mocktails-box">
ul instead of div

2024-02-20 09:40 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +                    <div class="col-lg-3 col-md-6 col-sm-6 align-self-center mb-30 properties-items col-md-6" data-tag="{{ mocktail['category_id'] }}">
li instead of div

2024-02-20 09:40 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +                        <div class="item text-center" data-product-name="{{ mocktail.name }}">
article instead of div

2024-02-20 09:54 UTC, Benja-san requested changes

2024-02-20 09:54 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +<div class="section mocktails">
use main tag instead of div tag

2024-02-20 09:54 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +        <article class="row mocktails-box">
section instead oif article, you will display a list of articles

2024-02-20 09:54 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +        <article class="row mocktails-box">
or you can use ul

2024-02-20 09:54 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +            <div
li instead of div tag

2024-02-20 13:23 UTC, Benja-san requested changes

2024-02-20 13:23 UTC, Benja-san commented on templates/mocktail/index.html.twig
> +                        <li
li inside li

2024-02-20 13:50 UTC, joelmayemba approved these changes

2024-02-20 14:24 UTC, Benja-san requested changes

2024-02-20 14:24 UTC, Benja-san commented on src/Controller/MocktailController.php
> +    #[Route('/', name: 'index')]
think about the underscore after "app_moktail" or before "index"

2024-02-20 14:24 UTC, Benja-san commented on src/Controller/MocktailController.php
> +    #[Route('/show', name: 'show')]
same for show route name

2024-02-20 14:58 UTC, Benja-san approved these changes

2024-02-20 14:58 UTC, merged