Add CSS to symfony project
WildCodeSchool/Rogue-One_Symfony pull request #6
Opened 2024-02-19 16:00 UTC by joelmayemba

2024-02-19 16:12 UTC, chouaibj approved these changes

2024-02-19 16:26 UTC, Benja-san requested changes

2024-02-19 16:26 UTC, Benja-san commented on assets/styles/app.css
> +.sub-header a:hover {
Saw this class into the navbar html, remove it from navbar stylesheet if general behavior. Else remove it from here if it is only linked to layout navbar (and put it into navbar css file)

2024-02-20 09:15 UTC, Benja-san requested changes
Keep phpstan.neon, and organize you css files

2024-02-20 14:51 UTC, Benja-san approved these changes

2024-02-20 14:54 UTC, merged