Add navbar to symfony project
WildCodeSchool/Rogue-One_Symfony pull request #8
Opened 2024-02-19 16:02 UTC by joelmayemba

2024-02-19 16:13 UTC, chouaibj approved these changes

2024-02-19 16:24 UTC, Benja-san requested changes

2024-02-19 16:24 UTC, Benja-san commented on templates/base.html.twig
> +		{% block body %}{% endblock %}
what does block body refer to ?

2024-02-19 16:24 UTC, Benja-san commented on templates/base.html.twig
> +			{% block title %}Projet 3 Name
rename title

2024-02-19 16:24 UTC, Benja-san commented on templates/base.html.twig
> +		{% block header %}{% endblock %}
what this header block is made for ?

2024-02-19 20:02 UTC, chouaibj approved these changes

2024-02-20 09:28 UTC, Benja-san requested changes

2024-02-20 09:28 UTC, Benja-san commented on templates/partials/_navbar.html.twig
> +{% block navbar %}
you don't have to precise this block since you're including it inside the same block in your base file

2024-02-20 09:28 UTC, Benja-san commented on assets/styles/components/navbar.css
All your header and navbnar style is here! Yopu can remove it from app.css in the other branch

2024-02-20 13:48 UTC, Benja-san requested changes

2024-02-20 13:48 UTC, Benja-san commented on assets/styles/app.scss
>  @import "wcs";
do you need that ?

2024-02-20 13:48 UTC, Benja-san commented on assets/styles/app.scss
>  @import "wcs";
Remove useless imports / files

2024-02-20 13:48 UTC, Benja-san commented on assets/styles/styles.css
> +    .mocktails .item ul li {
why is there moktails and ocntact rules inside your global css file ?

2024-02-20 14:25 UTC, Benja-san approved these changes

2024-02-20 14:25 UTC, Benja-san commented on webpack.config.js
> +    .addStyleEntry('footer', './assets/styles/components/navbar.css')
if you want you can include all global and layout css files into app.js and it will automatically be charged thanks to the entry_link_tags option

2024-02-20 14:26 UTC, merged