Migration of page Home with css
WildCodeSchool/Rogue-One_Symfony pull request #9
Opened 2024-02-19 16:07 UTC by chouaibj

2024-02-19 16:21 UTC, Benja-san requested changes

2024-02-19 16:21 UTC, Benja-san commented on src/Controller/HomeController.php
> +            'pageName' => 'Home',
French for better fit with french content

2024-02-19 16:21 UTC, Benja-san commented on templates/home/index.html.twig
> +{% block content %}
no H1 no main tag

2024-02-20 09:51 UTC, Benja-san requested changes

2024-02-20 09:51 UTC, Benja-san commented on templates/home/index.html.twig
> +<div id="carouselExampleAutoplaying"
main tag instead of div tag

2024-02-20 09:51 UTC, Benja-san commented on templates/home/index.html.twig
> +    <div class="main-banner">
use section / ul and li tags for better referencing

2024-02-20 13:21 UTC, Benja-san requested changes

2024-02-20 13:21 UTC, Benja-san commented on templates/home/index.html.twig
> +                            <h1>A venir...<br /></h1>
h2

2024-02-20 13:45 UTC, Benja-san approved these changes

2024-02-20 13:49 UTC, joelmayemba approved these changes

2024-02-20 13:58 UTC, merged